### ISSUE TITLE
subDossierNumber Unknown

### ISSUE THREAD

**Issue by FdjNL** [jfversluis/OverheidioApi.Net#2]
there is a error in the kvk lookup.

some results have no subDossierNumber or dont return them on a lookup.
try searching for "Vereniging van Eigenaars" for some examples

so the requierd string in the public async Task<Corporation> GetCorporation(string dossierNumber, string subdossierNumber)
can't be filled.

**Comment by jfversluis** [comment]
It's been forever since I had a look at this, but thanks!

If it's something you can fix I'd be happy to take a PR.

**Comment by FdjNL** [comment]
the api endpoind is also changed and there are some other beaking changes on the api.
going to try and convert it to the new endpoint

**Comment by jfversluis** [comment]
That would be awesome, thanks! :)

**Comment by jfversluis** [comment]
Merged #3 a new Nuget should be rolling out any minute. Can you confirm if it works for you?

**Comment by FdjNL** [comment]
NuGet still shows the 1.0.9 version

**Comment by jfversluis** [comment]
Yeah got an email that there is some delay with publishing the package.. Will let you know!

**Comment by jfversluis** [comment]
And just as I pressed send I got a message saying that it has been published.
